services:
  api:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - PORT=80
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shopper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
