services:
  api:
    build: .
    ports:
      - "80:80"
    env_file:
      - .env
    networks:
      - shopper-image-api
    environment:
      - PORT=80
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: shopper
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - shopper-image-api_pgdata:/var/lib/postgresql/data
    networks:
      - shopper-image-api

networks:
  shopper-image-api:
    driver: bridge

volumes:
  shopper-image-api_pgdata:
    driver: local
